const express=require('express');
const cors=require('cors');
const connectdb=require('./db');
const postRoutes=require('./routes/postRoutes.js');
require('dotenv').config();
const app=express();
app.use(cors());
app.use(express.json());
app.use('/api/posts',postRoutes);
connectdb();
app.listen(5000, () => console.log("Server running on port 5000"));
